# Generated by Django 5.2.7 on 2025-10-22 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose_cakes', '0002_category_coupon_order_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='Weight in kg', max_digits=5),
        ),
    ]
