# Generated by Django 5.2.7 on 2025-10-23 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose_cakes', '0003_cake_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage (e.g., 10 for 10%)', max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount (alternative to percentage)', max_digits=10)),
                ('minimum_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order value to apply offer', max_digits=10)),
                ('active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='offers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='special_offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rose_cakes.specialoffer'),
        ),
    ]
