# Generated by Django 5.2.7 on 2025-11-03 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose_cakes', '0004_specialoffer_order_special_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Rose Cakes', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Upload site logo', null=True, upload_to='site/')),
                ('hero_image', models.ImageField(blank=True, help_text='Main hero image for homepage', null=True, upload_to='site/')),
                ('about_image_1', models.ImageField(blank=True, help_text='About section image 1', null=True, upload_to='site/')),
                ('about_image_2', models.ImageField(blank=True, help_text='About section image 2', null=True, upload_to='site/')),
                ('about_image_3', models.ImageField(blank=True, help_text='About section image 3', null=True, upload_to='site/')),
                ('about_image_4', models.ImageField(blank=True, help_text='About section image 4', null=True, upload_to='site/')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL', null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL', null=True)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL', null=True)),
                ('email', models.EmailField(blank=True, help_text='Contact email address', max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='Site meta description for SEO', null=True)),
                ('meta_keywords', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
