# Generated by Django 5.2.7 on 2025-11-03 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rose_cakes', '0005_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='store_description',
            field=models.TextField(blank=True, help_text='Store description', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number', max_length=20, null=True),
        ),
    ]
