# Generated by Django 5.2.7 on 2025-11-06 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rose_cakes', '0007_remove_order_customer_address_order_pickup_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_id',
        ),
    ]
